name: ${project.name}
version: ${project.version}
main: net.cyberflame.rankpicker.RankPicker
depend: [PlaceholderAPI]
authors: [CyberFlame]
description: Force new players to pick a rank on join through a container menu
commands:
  rankpicker:
    description: Rank picking admin commands
permissions:
  rankpicker.admin:
    description: ability to use admin commands
    default: op
  rankpicker.close:
    description: menu no longer persists/gets given on join
    default: false
